name: xai4PVnBEV
channels:
  - conda-forge
dependencies:
  - geopandas=1.0.1
  - lightgbm=4.5.0
  - matplotlib=3.9.2
  - numpy=1.26.4
  - openpyxl=3.1.5
  - pandas=2.2.2
  - pyproj=3.6.1
  - python=3.12.5
  - scikit-learn=1.5.1
  - scipy=1.14.1
  - seaborn=0.13.2
  - shap=0.45.1
  - shapely=2.0.6
  - tikzplotlib=0.10.1
