name: xai4PVnBEV
channels:
  - conda-forge
dependencies:
  - geopandas=1.0.1
  - lightgbm=3.3.5
  - numpy=1.26.4
  - openpyxl=3.1.5
  - openssl=3.3.1
  - packaging=24.1
  - pandas=2.2.2
  - pyproj=3.6.1
  - python=3.11.9
  - scikit-learn=1.3.0
  - scipy=1.14.1
  - seaborn=0.13.2
  - shap=0.41.0
  - shapely=2.0.6
  - tikzplotlib=0.10.1
  - tqdm=4.66.5
 