name: xai4PVnBEV
channels:
  - conda-forge
dependencies:
  - geopandas=0.12.2
  - lightgbm=3.3.5
  - numpy=1.23.5
  - pandas=1.1.3
  - pyproj=3.6.1
  - python=3.9.19
  - scikit-learn=1.5.1
  - scipy=1.13.1
  - seaborn=0.12.2
  - shap=0.41.0
  - shapely=2.0.6
  - tqdm=4.66.5
